version: "2"
services:
  radiotgrabbing:
    build:
      context: ./
      args:
        JAR_FILE: ./*radiot2telegram-*.jar
        ENTRY_POINT: ./entry_point.sh
    container_name: radiot2telegram.anagorny.com
    volumes:
      - /tmp/:/tmp/
    env_file:
      - ENV_INIT.env