#Web-server params
server:
  port: ${PORT:8080}

#Telegram params
telegram:
  chat-id: ${TG_CHANNEL_ID}
  bot:
    token: ${TG_BOT_TOKEN}
    name: ${TG_BOT_NAME}
  sending:
    ignore-error: false
    retry:
      max-attempts: 3
      delay: 10000
  files:
    audio-max-size: 47MB

#RiteKit API params
hashtags:
  enabled: true
  count: 5
  api:
    token: ${RITEKIT_CLIENT_ID}
    url: https://api.ritekit.com/v1/stats/hashtag-suggestions

system:
  #Main params
  work-dir: ${WORK_DIR}
  #System metadata params
  metadata-path: ${WORK_DIR}/metadata_${TG_CHANNEL_ID}.json

#FFmpeg params
media:
  work-dir: ${FFMPEG_WORK_DIR}
  ffmpeg:
    path: ${FFMPEG_PATH}
  ffprobe:
    path: ${FFPROBE_PATH}
#  params:
#    mp3:
#      channels: 1

#Concurency params
parallel:
  core-size: ${PARALLEL_CORE}
  max-size: ${PARALLEL_MAX}

rss:
  #Archive feed params
  archive:
#    url: https://radio-t.com/podcast-archives.rss # It doesn't parse now
    url: http://feeds.rucast.net/radio-t
    batch-size: ${BATCH_SIZE}
  #Main feed params
  main:
    url: http://feeds.rucast.net/radio-t
    cron:
      - "*/10 * 22-23 ? * SAT *"
      - "*/10 * 0-9 ? * SUN *"

#Downloader params
download:
  connection-timeout: 15s
  read-timeout: 60s
  retry:
    max-attempts: 3
    delay: 10000

#Logging params
logging:
  level:
    root: INFO
  file:
    name: ${WORK_DIR}/logs/radiot2telegram.log
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 10MB
